version: '3.8'

services:
  app:
    image: folio-app-backend:0.0.1-SNAPSHOT
    container_name: folio-app-backend
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: folio
#    volumes:
#      - ../../data:/var/lib/postgresql/data