# JPA and Datasource configuration settings
spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/folio-dev
    username: postgres
    password: postgres