CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   legal_name VARCHAR(75) NOT NULL,
   cnpj VARCHAR(14) NOT NULL,
   tickers TEXT[] NOT NULL,
   broker BOOLEAN NOT NULL,
   listed BOOLEAN NOT NULL,
   CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies ADD CONSTRAINT UniqueLegalNameAndCnpj UNIQUE (legal_name, cnpj);

CREATE INDEX fn_index ON companies(cnpj);