name: Java CI Version

on:
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      RELEASE_VERSION: ${{ steps.release.outputs.version }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml -ntp

      - name: Get Maven Version
        id: get-maven-version
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "MAVEN_VERSION=${MAVEN_VERSION}" >> $GITHUB_ENV

      - name: Extract and Display Version
        id: version
        run: |
          version=$(echo $MAVEN_VERSION | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=${version}" >> $GITHUB_ENV
          echo "Using Release Version: $version"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.version}}
        run: echo "$OUTPUT1"