name: Java CI Version

on:
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.build.outputs.version }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -ntp

      - id: build
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.version }}
        run: echo "$OUTPUT1"

      - name: Extract and Display Version
        run: |
          echo "formatted_version=$(${{ needs.job1.outputs.version }} | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"
          echo "Formatted Version: $formatted_version"